### ISSUE TITLE
Icons too small

### ISSUE THREAD

**Issue by antgel** [fourkitchens/hipchat-emoticons#12]
I clone the (great!) repo, but the icons are too small.  PEBKAC?  What did I miss?

**Comment by astanush** [comment]
These icons were created before the [requirements changed to a minimum size of 64x64](https://blog.hipchat.com/2014/12/05/goodnews-new-and-improved-emoticons/). We haven't got around to resizing them yet.

**Comment by astanush** [comment]
We're on Slack now. Won't fix.
