### ISSUE TITLE
Add (eliaface) to the 4K emoticons

### ISSUE THREAD

**Issue by feliarex** [fourkitchens/hipchat-emoticons#15]
![img_1519](https://cloud.githubusercontent.com/assets/5611997/5923106/7c038cba-a616-11e4-9d0c-d2dd90a382c7.jpg)

**Comment by rupl** [comment]
you're too big

**Comment by feliarex** [comment]
yeah, no kidding. I'm just giving him the file, you momo.

**Comment by flipstewart** [comment]
![7c038cba-a616-11e4-9d0c-d2dd90a382c7](https://cloud.githubusercontent.com/assets/1306968/5923202/402194c0-a617-11e4-8188-4179b081dee9.jpg)

Went ahead and resized it for you.

**Comment by rupl** [comment]
too small

**Comment by feliarex** [comment]
It's like Goldilocks over here. When will it be "just right"?

**Comment by flipstewart** [comment]
.tumblr.com

**Comment by feliarex** [comment]
![screen shot 2015-01-27 at 11 28 31 am](https://cloud.githubusercontent.com/assets/5611997/5923261/c345c380-a617-11e4-90c4-45de33d263ca.png)

**Comment by flipstewart** [comment]
OH I GET IT NOW

**Comment by patrickocoffeyo** [comment]
120px x 120px is truly the optimal

**Comment by feliarex** [comment]
@patrickocoffeyo yes, yes. and this way, Aaron can resize it as he sees fit.

**Comment by mattgrill** [comment]
![eliaface](https://cloud.githubusercontent.com/assets/1090713/5924571/c982b6dc-a611-11e4-8561-3b1419e20f3c.png)

**Comment by feliarex** [comment]
:+1: @mattgrill

**Comment by flipstewart** [comment]
![ezgif com-maker](https://cloud.githubusercontent.com/assets/1306968/5924888/0f6877be-a625-11e4-96f0-9331952c86a2.gif)

**Comment by feliarex** [comment]
Even better @flipstewart

**Comment by mattgrill** [comment]
@flipstewart @feliarex Create a PR to get this merged in.

**Comment by flipstewart** [comment]
@mattgrill I was hoping for more rebounds...

**Comment by mattgrill** [comment]
![elia2](https://cloud.githubusercontent.com/assets/1090713/5929176/2f76219e-a636-11e4-989a-1d525a4790a3.gif)

**Comment by feliarex** [comment]
Too small. I can't even tell who that is now.

On Tue, Jan 27, 2015 at 5:07 PM, Matthew Grill <notifications@github.com>
wrote:

> [image: elia2]
> <https://cloud.githubusercontent.com/assets/1090713/5929176/2f76219e-a636-11e4-989a-1d525a4790a3.gif>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fourkitchens/hipchat-emoticons/issues/15#issuecomment-71748025>
> .
>



-- 
Elia Albarran
Operations Manager
Four Kitchens <http://fourkitchens.com/>: Big ideas for the web
